#!/bin/bash
cd $HOME/ext
for proj in $(ssh mcgaffin@git.greyhill.me 'cd /media/git && ls .'); do
    echo "Checking $proj..."
    if [ ! -d $proj ]; then
        echo "Doesn't exist locally, cloning"
        git clone ssh://mcgaffin@git.greyhill.me/media/git/$proj
    fi
    cd $proj && git fetch origin && cd ..
done
