#!/bin/bash
cd $HOME/ext
for proj in $(ssh greyhill@fenchel.local 'cd /opt/git && ls .'); do
    echo "Checking $proj..."
    if [ ! -d $proj ]; then
        echo "Doesn't exist locally, cloning"
        git clone ssh://greyhill@fenchel.local/opt/git/$proj
    fi
    cd $proj && git pull origin master && git push origin master && \
        ((cat .nocontent && git annex sync) || git annex sync --content)
    cd $HOME/ext
done
